### ISSUE TITLE
CloudFormation Setup of Backend

### ISSUE THREAD

**Issue by AcidLeroy** [AnomalyInnovations/serverless-stack-com#107]
For this tutorial I think it is great that you walk through creating the all the resources by hand so you can describe why you are doing it. But I also think as additional chapter it may be worth putting a YAML file together describing the system using cloud formation templates. This makes deleting and creating the app a lot easier. I'm curious if anyone else has attempted to do this? I've been attempting to create the necessary template as I read along, but I got a bit stuck at the new identity pool portion. It's not clear to me how to properly setup the cloudformation template for this part of the resource creation. Here is what I have: 

```
resources:
  Resources:
    ScratchAppDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes_serverless
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    
    ScratchAppS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: scratchbucket505
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT, POST, HEAD]
              AllowedOrigins: ['*']
              MaxAge: '3000'

    ScratchUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: notes-user-pool

    ScratchUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: notes-client
        ExplicitAuthFlows: [ADMIN_NO_SRP_AUTH]
        UserPoolId:
          Ref: ScratchUserPool

    ScratchIdentityPool: # <------------------------THIS IS BROKEN
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: ScratchIdentityPool
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          - ClientId:
              Ref: ScratchUserPoolClient
            ProviderName:
              Ref: ScratchUserPool

```
