### ISSUE TITLE
authorizer aws_iam ?

### ISSUE THREAD

**Issue by rudyhadoux** [AnomalyInnovations/serverless-stack-com#251]
Hi,

Why don't you use a Cognito authorizer ?
Like that :

```
functions:
  create:
    handler: rdvs/create.create
    events:
      - http:
          path: rdvs
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-1:312xxx469185:userpool/eu-west-1_jiKxxxfUu
```
