### ISSUE TITLE
Missing WebPack config in cross-stack setup

### ISSUE THREAD

**Issue by ahallora** [AnomalyInnovations/serverless-stack-com#329]
The [article describing support for cross-stack references]( https://serverless-stack.com/chapters/api-gateway-domains-across-services.html) is missing support for ES6 compiling with Webpack using the plugin [serverless-webpack](https://www.npmjs.com/package/serverless-webpack) as you do in the other part of the tutorial. 

Consider adding this to the serverless.yml - with a reference to the actual package.json: 

```yml
  # Load our webpack config
  webpack:
    webpackConfig: ./../../webpack.config.js
    includeModules:
      packagePath: '../../package.json'
```
