### ISSUE TITLE
S3 bucket should have etag header exposed

### ISSUE THREAD

**Issue by liebrand** [AnomalyInnovations/serverless-stack-com#485]
Just found that any half decent sized file for upload will fail, because amplify storage falls over if the s3 bucket does not have the etag exposed.

Simple fix to the CORS setup... in yml:
```
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
            ExposedHeaders:
              - ETag
```
