### ISSUE TITLE
Comments: Save Changes to a Note

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#55]
Link to chapter - http://serverless-stack.com/chapters/save-changes-to-a-note.html

**Comment by SherpaPsy** [comment]
Perhaps I am getting ahead of myself here, but if I edit a note - and select a new attachment, the new attachment is uploaded, but the original attachment is still there. Is this intended? Oh, and once again, I am amazed by the quality of this work and your tutorial on it, even though I am not a developer and the code is way over my head.

**Comment by jayair** [comment]
@SherpaPsy you are right, we don't handle that case. And we don't take care of the attachment, when we delete a note. For the sake of simplicity, we leave a lot of these up to you.

I'll add a note making that clear so it doesn't confuse people.

**Comment by jayair** [comment]
Added a note regarding the attachment - 41987fbd9795f997f6bc06feb02efc9665cf7c85

**Comment by toddmcneill** [comment]
I attempted to delete the file from S3 when attaching a new file.
I read the documentation and built a function patterned after the s3Upload function, but it just wouldn't work. I finally found that you need to add a line to the S3 bucket's CORS configuration:
`<AllowedMethod>DELETE</AllowedMethod>`
Once I did that, I encountered no more errors. Here's some sample code:

In awsLib.js, add
```
export async function s3Delete(key, userToken){
  await getAwsCredentials(userToken);
  
  const s3 = new AWS.S3({
    params: {
      Bucket: config.s3.BUCKET,
    }
  });

  return s3.deleteObject({
    Key: key,
  }).promise();
}
```

In the handleSubmit function of Notes.js, under the line `if (this.file) {`, add
```
let fileKey = decodeURIComponent(new URL(this.state.note.attachment).pathname.substring(1));
await s3Delete(fileKey, this.props.userToken);
```
This parses the S3 object key out of the URL and uses it to delete the S3 object. It would probably be better practice to store both the URL and the S3 object key in the first place rather than storing only the URL.

**Comment by jayair** [comment]
@toddmcneill Thanks for writing it up. There's a PR that I'll be merging soon to add this in.

**Comment by jomazu** [comment]
@toddmcneill Thanks for the write up! I also added `s3Delete` to `import { invokeApig, s3Upload, s3Delete } from '../libs/awsLib';` in `Notes.js` header. However, I still cannot seem to get this to work properly? Can you point me to the documentation you read to figure this out? jz

**Comment by jayair** [comment]
@jomazu Did you add `<AllowedMethod>DELETE</AllowedMethod>` to the the CORS configuration for the S3 bucket?

**Comment by jomazu** [comment]
@jayair Thanks for the follow up! I did add `<AllowedMethod>DELETE</AllowedMethod>` to the CORS config in AWS. However, whenever I select the Delete bar, the spinner just continues spinning endlessly... When I get some free time, I will look into this further.

**Comment by d3sandoval** [comment]
I'm having a problem calling the PUT method. I get the following error in the console when I hit the submit button:
```
972e7390-74a1-11e7-9b16-adf6e59582b7:1 Fetch API cannot load https://<my-endpoint>.execute-api.us-east-1.amazonaws.com/prod/notes/972e7390-74a1-11e7-9b16-adf6e59582b7. No 'Access-Control-Allow-Origin' header is present on the requested resource.

Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Notes.js:100 TypeError: Failed to fetch
```

I've double-checked my serverless.yml file and it seems to match what is expected at this point in the tutorial:
```
service: notes-app-api

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1

  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  create:
    # Defines an HTTP API endpoint that calls the main function in create.js
    # - path: url path is /notes
    # - method: POST request
    # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
    #     domain api call
    # - authorizer: authenticate using the AWS IAM role
    handler: create.main
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam

  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /notes/{id}
    # - method: GET request
    handler: get.main
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
          authorizer: aws_iam

  list:
  # Defines an HTTP API endpoint that calls the main function in list.js
  # - path: url path is /notes
  # - method: GET request
    handler: list.main
    events:
      - http:
          path: notes
          method: get
          cors: true
          authorizer: aws_iam


  update:
  # Defines an HTTP API endpoint that calls the main function in update.js
  # - path: url path is /notes/{id}
  # - method: PUT request
    handler: update.main
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
          authorizer: aws_iam

  delete:
  # Defines an HTTP API endpoint that calls the main function in update.js
  # - path: url path is /notes/{id}
  # - method: PUT request
    handler: delete.main
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
          authorizer: aws_iam
```

Any help is appreciated
